name: Azure Container Apps Deploy

on:
  push:
    branches:
      - develop
env:
  ACR_NAME: testacrnamefrfdwedwe
  RESOURCE_GROUP: oleg-rg
  APP_NAME: api
  ENVIRONMENT: new-environment
  LOCATION: westeurope
  SUBSCRIPTION_ID: ff3fd8a8-04ee-41dd-8b5f-ac85fd217054

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          appSourcePath: ${{ github.workspace }}
          acrName:  ${{ env.ACR_NAME }}
          containerAppName: ${{env.APP_NAME}}
          resourceGroup:  ${{env.RESOURCE_GROUP}}


