name: Development deploy

on:
  push:
    branches:
      - devs

env:
  AZURE_FUNCTIONAPP_NAME: kith-function-app    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x, 14.x)
  RESOURCE_GROUP: my-test-group
  DIST_FOLDER: dist
  FUNC_FOLDERS: User Auth

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          yarn install 
          yarn  build  
          mv node_modules ${{env.DIST_FOLDER}}
          popd
      - name: 'Run Azure Functions action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.DIST_FOLDER }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  # deploy-front:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Upload to blob storage
  #       uses: azure/CLI@v1
  #       with:
  #         inlineScript: |
  #           az storage blob upload-batch --account-name staticsidrvymiuyt --auth-mode key -d '$web' -s static/ --overwrite=true

  #     # Azure logout
  #     - name: logout
  #       run: |
  #         az logout
  #       if: always()

